### ISSUE TITLE
Check the prototype with willing subjects only

### ISSUE THREAD

**Issue by minijackson** [BDE-ESIEE/API-canteen-watcher#1]
Do NOT check the prototype in an open/public place, without the consent of the people in it.

**Comment by mininao** [comment]
Prototype is offline haha

Sent using CloudMagic Email
[https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.0.55&pv=5.1.1&source=email_footer_2] On Thu, Nov 12, 2015 at 12:40 PM, Minijackson < notifications@github.com [notifications@github.com] > wrote:
Do NOT check the prototype in an open/public place, without the consent of the
people in it.
